import Meta from '../components/Meta';
import './Page.css';

export default function About() {
  return (
    <div className="page-wrap">
      <Meta
        title="About Us – Salary Calculator UK | Free UK Pay Calculator"
        description="Learn about Salary Calculator UK — a free tool helping UK workers calculate their take-home pay after income tax, NI, pension and student loan deductions."
      />
      <div className="page-container">
        <div className="page-header">
          <h1>About Salary Calculator UK</h1>
          <p>Free, accurate, and easy-to-use UK salary tools for everyone.</p>
        </div>

        <div className="page-content">
          <section>
            <p>
              Salary Calculator UK is a free online platform designed to help individuals across the
              United Kingdom understand their earnings, taxes, and deductions with confidence. Whether
              you're employed, self-employed, working in the public sector, or planning your finances,
              our calculators provide fast and easy-to-understand estimates based on current UK tax
              regulations.
            </p>
            <p>
              Understanding payslips, tax deductions, National Insurance contributions, pension payments,
              and student loan repayments can often be confusing. Our goal is to simplify these
              calculations and provide clear insights into how your income is affected by UK tax rules.
            </p>
          </section>

          <section>
            <h2>Our Calculators and Tools</h2>
            <p>We offer a growing range of free financial calculators and resources, including:</p>
            <div className="about-tool-card">
              <h3>UK Salary &amp; Take-Home Pay Calculator</h3>
              <p>
                Estimate your net salary after Income Tax, National Insurance, workplace pension
                contributions, student loan deductions, salary sacrifice arrangements, bonuses,
                overtime payments, dividends, and savings income.
              </p>
            </div>
          </section>

          <section>
            <h2>How We Maintain Accuracy</h2>
            <p>
              Our calculation systems are built using publicly available information from HM Revenue
              &amp; Customs (HMRC) and other official UK government sources. We regularly review and
              update tax rates, thresholds, allowances, and contribution limits whenever changes are
              announced.
            </p>
            <p>Our calculators are designed to reflect the latest available tax year information, including:</p>
            <ul>
              <li>Income Tax rates and thresholds</li>
              <li>National Insurance contributions</li>
              <li>Student Loan repayment plans</li>
              <li>Postgraduate Loan deductions</li>
              <li>Workplace pension contributions</li>
              <li>Dividend and savings income taxation</li>
              <li>Child Benefit and related tax charges</li>
            </ul>
            <p>
              We continually test and refine our calculations to provide reliable estimates that closely
              reflect official guidance.
            </p>
          </section>

          <section>
            <h2>Why Use Salary Calculator UK?</h2>
            <ul>
              <li>Free and easy-to-use online calculators</li>
              <li>Updated with the latest UK tax and payroll information</li>
              <li>Support for England, Wales, Northern Ireland, and Scotland tax rules</li>
              <li>Detailed breakdowns of deductions and take-home pay</li>
              <li>Mobile-friendly design for use on any device</li>
              <li>Instant results with no registration required</li>
              <li>Useful tools for employees, NHS staff, teachers, contractors, and employers</li>
            </ul>
          </section>

          <section>
            <h2>Important Information</h2>
            <p>
              While we work hard to ensure the accuracy of every calculation, the UK tax system is
              complex and subject to regular changes. The results generated by our calculators should
              be used as estimates and guidance only. Individual circumstances may affect actual tax
              liabilities and take-home pay.
            </p>
            <p>
              For decisions involving taxation, payroll, pensions, or financial planning, we recommend
              consulting <a href="https://www.gov.uk/government/organisations/hm-revenue-customs" target="_blank" rel="noopener noreferrer">HMRC</a> or
              a qualified financial professional.
            </p>
          </section>

          <section>
            <h2>How We Fund the Website</h2>
            <p>
              Salary Calculator UK is provided free of charge to all users. To support ongoing
              development, maintenance, and updates, the website may display advertising and other
              forms of revenue-generating content.
            </p>
          </section>

          <section>
            <h2>Our Commitment</h2>
            <p>
              Our mission is to make salary, tax, and financial calculations easier to understand for
              everyone in the UK. We are committed to providing practical tools, accurate information,
              and a straightforward user experience that helps users make informed financial decisions.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
